apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base manifests shared by all environments
resources:
  - ../../base

namespace: dev-banking

commonLabels:
  env: dev
  app.kubernetes.io/environment: dev

namePrefix: dev

# You can later add patches here to override image tags, replicas, etc.
# patchesStrategicMerge:
#   - deployment-patch.yaml
